# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: /connexion/
                check_path: /login_check
            logout:
                path:   /logout
                target: / 
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER        
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/apropos/, roles: ROLE_USER }
        # Include the following line to also secure the /admin path itself
        # - { path: ^/admin$, roles: ROLE_ADMIN }

    providers:
        users:
            entity: { class: Wf3\KikaBundle\Entity\User, property: email}
    #    in_memory:
    #        memory:
    #            users:
    #                ryan:  { password: ryanpass, roles: 'ROLE_USER' }
    #                admin: { password: kitten, roles: 'ROLE_ADMIN' }

    encoders:
        Wf3\KikaBundle\Entity\User: 
            algorithm: sha512
            #Symfony\Component\Security\Core\User\User: plaintext

    #être admin donne tous les droits qu'ont les users
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER