<?php

namespace Wf3\KikaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingRepository extends EntityRepository
{


	public function findKikalaFormations () {

		//$query = $this->getEntityManager()->createQuery('SELECT con, cat FROM Wf3KikaBundle:User con LEFT JOIN con.category cat '); 

		//$kikologuesInscrits = $query->getResult();

		//return $contents;


		$count = $this->createQueryBuilder('training')
                 ->select('COUNT(training)')
                 ->andWhere('training.status = 1')
                 ->getQuery()
                 ->getSingleScalarResult();

       // echo ($count);  j ai  0        
       
        return $count;

    }    


}
